#!/usr/bin/env sh

if [ "$1" = "entrypoint" ]; then
  # Bootstrap
  addgroup -g "$4" "$2"
  adduser -h /home/dev -D -s /bin/sh -u "$3" -G "$2" "$2"
  php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  php composer-setup.php --install-dir=/usr/bin --filename=composer
  php -r "unlink('composer-setup.php');"
  # Enter Shell
  if [ "$5" = "root" ]; then sh; else su -c '/bin/sh' "$2"; fi
else
  # Launch container
  docker run \
	--interactive --tty --rm \
	--volume $(pwd):/home/dev/src -w /home/dev/src \
	--env "PS1=\e[1;32m\u@php-λ \e[1;34m\w\e[1;39m $ \e[0;39m" \
	php:7.1-rc-alpine \
	./workspace entrypoint $(id -u -n) $(id -u) $(id -g) ${@}
fi
